### ISSUE TITLE
Docker Agent  shows disk full 

### ISSUE THREAD

**Issue by superim** [kasmtech/workspaces-images#88]
Hi Guys,

I have a problem with my Docker Agent.  It shows the disk is full after I deleted all unnecessary files and folders. That is why I can not run a new workspace. 
Is there any way to refresh the disk size on the agent? 
Thank you for the advice in advance.

<img width="1094" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/48853689/319607be-ad46-4a94-914b-e0d3866eb03d">

**Comment by mmcclaskey** [comment]
When is the last time your agent checked in? The stats get updated every time it checks in, but if the services are not running, for example, it will not check in. It is possible that running out of disk space caused the agent container to crash. Run the following and ensure in the Kasm UI the agent is showing as checked in in the past 60 seconds max.

```bash
/opt/kasm/bin/stop
/opt/kasm/bin/start
```

**Comment by superim** [comment]
Thank you for your response. 
Yes, I did many times stop/start also rebooted the server as well. Unfortunately, the Agent didn't realize the new disk-free size.

This is from the Agent view page:
<img width="433" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/48853689/b0e22f73-17b3-434e-bed1-233bb5259ae0">

I can verify I have %38 free space on the command line; 
<img width="350" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/48853689/6d7a254a-910e-4802-8899-207de9707033">

**Comment by superim** [comment]
What if I delete the agent session? Can I delete and create it again? 
<img width="707" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/48853689/c8834b5e-b7c0-4898-a8c7-cd6fa32cd37b">

**Comment by mmcclaskey** [comment]
can you provide the output of....

```bash
sudo docker ps -a
sudo docker logs --tail 300 kasm_agent
```

**Comment by superim** [comment]
`Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[10] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[10] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[10] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[10] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[8] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
Executing /usr/bin/kasm_agent.so
Received config /opt/kasm/current/conf/app/agent.app.config.yaml
Traceback (most recent call last):
  File "__init__.py", line 759, in <module>
TypeError: 'NoneType' object is not subscriptable
[9] Failed to execute script '__init__' due to unhandled exception!
`

**Comment by superim** [comment]
Finally, I've created a new agent.app.config.yaml file from the template.
After restarting the services The Agent checked in successfully and I was able to create a new workspace. 

Thank you @mmcclaskey 🙏🏻

Now the ticket can be closed.
